/**
 * Report export links (V3 §20.2 Day 13 — report export).
 *
 * Each format is a plain link to the export route handler, which streams the
 * report generated by @forge/reporting as a downloadable attachment. No
 * client JavaScript is required; the route enforces auth + org scoping.
 */

import type { ReactNode } from "react";
import { Button } from "@forge/ui";
import { EXPORT_FORMATS } from "@/features/scans/report";

export interface ReportExportLinksProps {
  readonly jobId: string;
}

export function ReportExportLinks({ jobId }: ReportExportLinksProps): ReactNode {
  return (
    <div style={{ marginTop: "calc(var(--forge-spacing-unit) * 4)" }}>
      <h2 style={{ fontWeight: "var(--forge-typography-heading-weight)" }}>Export report</h2>
      <div style={{ display: "flex", gap: "calc(var(--forge-spacing-unit) * 2)", flexWrap: "wrap" }}>
        {EXPORT_FORMATS.map((format) => (
          <a key={format} href={`/scans/${jobId}/export?format=${format}`} data-testid={`export-${format}`}>
            <Button variant="secondary" size="sm">
              Export {format.toUpperCase()}
            </Button>
          </a>
        ))}
      </div>
    </div>
  );
}
